### PR TITLE
Improve Docker install procedure

### PR DESCRIPTION
**Pull request by CHTJonas**
I've neglected the Docker installation process a bit recently so this PR gives it a bit of TLC. I have tested on macOS & Windows and everything seems to be working acceptably.

@GKFX you mentioned in #49 that you had issues with this - any chance you could review and let me know if this works for you?

### CODE REVIEW

**Comment by GKFX** [comment]
This happens for me:
```
1|~/Geek/roombooking $ sudo docker-compose run --rm web "bin/setup"
Starting roombooking_db_1    ... done
Starting roombooking_cache_1 ... done
Configuring environment...
Enter your Camdram API App ID: 13_1xviwcd8hoe840w0w0s0oc4os4wo4w4ggsw80w4o8cogwcw44k
Enter your Camdram API App Secret: iwgb3j5qfxcg8gksk0gwkkog4004swwc0w0cg80wgcocs08wo

rails aborted!
PG::ConnectionBad: could not connect to server: Connection timed out
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1014:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/usr/src/app/bin/spring:15:in `require'
/usr/src/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => roombooking:docker => db:migrate
(See full trace by running task with --trace)

Command ["bin/rails roombooking:docker"] failed!
```

**Comment by CHTJonas** [comment]
That’s... interesting...

Can I ask what distro and version of Docker you are using? I’m going to try spinning up an entirely fresh VM on a cloud provider and see if I can reproduce.

**Comment by GKFX** [comment]
This is the output of reportbug, should contain everything needed.
```
docker-ce Version: 5:18.09.5~3-0~debian-buster
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'testing-proposed-updates'), (500, 'unstable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.19.0-4-amd64 (SMP w/4 CPU cores)
Kernel taint flags: TAINT_OOT_MODULE, TAINT_UNSIGNED_MODULE
Locale: LANG=en_GB.UTF-8, LC_CTYPE=en_GB.UTF-8 (charmap=UTF-8), LANGUAGE=en_GB:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages docker-ce depends on:
ii  containerd.io  1.2.5-1
ii  docker-ce-cli  5:18.09.5~3-0~debian-buster
ii  iptables       1.8.2-4
ii  libc6          2.28-8
ii  libseccomp2    2.3.3-4
ii  libsystemd0    241-3

Versions of packages docker-ce recommends:
ii  aufs-tools       1:4.14+20190211-1
ii  ca-certificates  20190110
ii  cgroupfs-mount   1.4
ii  git              1:2.20.1-2
ii  libltdl7         2.4.6-9
ii  pigz             2.4-1
ii  xz-utils         5.2.4-1

docker-ce suggests no packages.
```

**Comment by CHTJonas** [comment]
I'm wondering if it's a bug in Debian Testing or similar. I've just tested this on a cloud provider by spinning up a VM with Docker installed and running through the process in the new README. Unfortunately it's more difficult to spin up Buster VMs to test my theory...

**Comment by CHTJonas** [comment]
Just tested this in a Buster VM running inside VirtualBox and I did encounter a slightly different problem (which is fixed as of f2c71a6), but not the connection error that you experienced. I'm not sure but my guess is that it's somehow specific to your machine as Docker should figure out all the networking itself. Do you have anything that's interfering with Linux `iptables` such as UFW maybe?

**Comment by GKFX** [comment]
No, I don't believe I have anything like that. The only unusual networking software I have is my wifi driver, which is an out-of-tree kernel module. I could try disabling the module and trying again.

**Comment by GKFX** [comment]
Okay, I fiddled with my kernel modules a bit and got it working. Success!

**Pull request merged**
